name: Docker

on:
  push:
    schedule:
    - cron: '0 */5 * * * '
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: curl -d @data.json -H 'Content-Ttpe:application/json' https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5b271300-2f2c-4d48-abcb-ace4eaf43596
        