name: helloword

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  HelloWord:
    runs-on: ubuntu-latest
      - name: Print helloword
      run: |
        echo "12332131"