name: helloword

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  HelloWord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print helloword
      run: |
        bash docker.sh