name: helloword

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  HelloWord:
    runs-on: ubuntu-latest
      steps:
      - name: Print helloword
      env:
        H_L: Helloword
      run: |
        echo $H_L.