name: Docker

on:
  push:
    schedule:
    - cron: '0 */1 * * * '
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: curl -d @data.json -H 'Content-Ttpe:application/json' https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=712b8510-de86-4ce5-9855-c2904eeffe36