name: helloword

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  HelloWord:
    runs-on: ubuntu-latest
     steps:
    - name: Print a greeting
      env:
        MY_VAR: Helloword
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.